/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com_jFream;

import com_class.Universal;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;

/**
 *
 * @author CHETHANA
 */
public class mainHome extends javax.swing.JFrame {
 public static  Universal u = new Universal();
    /**
     * Creates new form mainHome
     */
    public mainHome() {
        initComponents();
        u.imageMethod("/img/hjk.png", jLabel1);
        u.imageMethod("/img/exit004.png", jLabel2);
        
        u.imageMethod("/img/invoice.png", img_invoice);
        u.imageMethod("/img/invoice.png", img_invoice2);
        u.imageMethod("/img/item.png", img_item);
        u.imageMethod("/img/stock.png", img_stock);
        u.imageMethod("/img/grn.png", img_grn);
        u.imageMethod("/img/supplier.png", img_supplier);
        u.imageMethod("/img/customer.png", img_customer);
        u.imageMethod("/img/item.png", img_item2);
        u.imageMethod("/img/stock.png", img_stock2);
        u.imageMethod("/img/grn.png", img_grn2);
        u.imageMethod("/img/supplier.png", img_supplier2);
        u.imageMethod("/img/customer.png", img_customer2);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        u.imageMethod("/img/logoP.png", Logo);
        
        name1.setText("<html>E<br>U<br>R<br>O</html>");
        name.setText("<html>P<br>A<br>R<br>T<br>S</html>");
        
        img_invoice2.setVisible(false); _invoice2.setVisible(false);
        img_item2.setVisible(false); _item2.setVisible(false);
        img_stock2.setVisible(false); _stock2.setVisible(false);
        img_grn2.setVisible(false); _grn2.setVisible(false);
        img_supplier2.setVisible(false); _supplier2.setVisible(false);
        img_customer2.setVisible(false); _customer2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        img_stock = new javax.swing.JLabel();
        _customer = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        img_invoice = new javax.swing.JLabel();
        _invoice = new javax.swing.JLabel();
        img_invoice2 = new javax.swing.JLabel();
        img_customer = new javax.swing.JLabel();
        _supplier = new javax.swing.JLabel();
        img_supplier = new javax.swing.JLabel();
        img_item = new javax.swing.JLabel();
        img_grn = new javax.swing.JLabel();
        _invoice2 = new javax.swing.JLabel();
        _item = new javax.swing.JLabel();
        _item2 = new javax.swing.JLabel();
        img_item2 = new javax.swing.JLabel();
        _stock = new javax.swing.JLabel();
        img_stock2 = new javax.swing.JLabel();
        _stock2 = new javax.swing.JLabel();
        _grn = new javax.swing.JLabel();
        img_grn2 = new javax.swing.JLabel();
        _grn2 = new javax.swing.JLabel();
        _supplier2 = new javax.swing.JLabel();
        img_supplier2 = new javax.swing.JLabel();
        _customer2 = new javax.swing.JLabel();
        img_customer2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Logo = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        name1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1376, 768));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1376, 768));
        getContentPane().setLayout(null);

        img_stock.setText("img_stock");
        img_stock.setBorder(new javax.swing.border.MatteBorder(null));
        img_stock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                img_stockMouseEntered(evt);
            }
        });
        getContentPane().add(img_stock);
        img_stock.setBounds(1020, 90, 200, 200);

        _customer.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        _customer.setForeground(new java.awt.Color(255, 255, 255));
        _customer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _customer.setText("CUSTOMER");
        _customer.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(_customer);
        _customer.setBounds(370, 640, 200, 30);

        jLabel2.setText("jLabel2");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 10, 40, 40);

        img_invoice.setText("img_invoice");
        img_invoice.setBorder(new javax.swing.border.MatteBorder(null));
        img_invoice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                img_invoiceMouseEntered(evt);
            }
        });
        getContentPane().add(img_invoice);
        img_invoice.setBounds(360, 90, 200, 200);

        _invoice.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        _invoice.setForeground(new java.awt.Color(255, 255, 255));
        _invoice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _invoice.setText("INVOICE");
        _invoice.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(_invoice);
        _invoice.setBounds(360, 290, 200, 30);

        img_invoice2.setText("img_invoice");
        img_invoice2.setBorder(new javax.swing.border.MatteBorder(null));
        img_invoice2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                img_invoice2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                img_invoice2MouseExited(evt);
            }
        });
        getContentPane().add(img_invoice2);
        img_invoice2.setBounds(320, 40, 290, 300);

        img_customer.setText("img_customer");
        img_customer.setBorder(new javax.swing.border.MatteBorder(null));
        img_customer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                img_customerMouseEntered(evt);
            }
        });
        getContentPane().add(img_customer);
        img_customer.setBounds(370, 440, 200, 200);

        _supplier.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        _supplier.setForeground(new java.awt.Color(255, 255, 255));
        _supplier.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _supplier.setText("SUPPLIER");
        _supplier.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(_supplier);
        _supplier.setBounds(1040, 640, 200, 30);

        img_supplier.setText("img_supplier");
        img_supplier.setBorder(new javax.swing.border.MatteBorder(null));
        img_supplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                img_supplierMouseEntered(evt);
            }
        });
        getContentPane().add(img_supplier);
        img_supplier.setBounds(1040, 440, 200, 200);

        img_item.setText("img_item");
        img_item.setBorder(new javax.swing.border.MatteBorder(null));
        img_item.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                img_itemMouseEntered(evt);
            }
        });
        getContentPane().add(img_item);
        img_item.setBounds(700, 90, 200, 200);

        img_grn.setText("img_grn");
        img_grn.setBorder(new javax.swing.border.MatteBorder(null));
        img_grn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                img_grnMouseEntered(evt);
            }
        });
        getContentPane().add(img_grn);
        img_grn.setBounds(700, 440, 200, 200);

        _invoice2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        _invoice2.setForeground(new java.awt.Color(16, 13, 13));
        _invoice2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _invoice2.setText("INVOIC");
        _invoice2.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(_invoice2);
        _invoice2.setBounds(340, 340, 240, 45);

        _item.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        _item.setForeground(new java.awt.Color(255, 255, 255));
        _item.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _item.setText("ITEM");
        _item.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(_item);
        _item.setBounds(710, 290, 200, 30);

        _item2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        _item2.setForeground(new java.awt.Color(16, 13, 13));
        _item2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _item2.setText("ITEM");
        _item2.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(_item2);
        _item2.setBounds(680, 340, 240, 45);

        img_item2.setText("img_item");
        img_item2.setBorder(new javax.swing.border.MatteBorder(null));
        img_item2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                img_item2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                img_item2MouseExited(evt);
            }
        });
        getContentPane().add(img_item2);
        img_item2.setBounds(660, 40, 290, 300);

        _stock.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        _stock.setForeground(new java.awt.Color(255, 255, 255));
        _stock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _stock.setText("STOCK");
        _stock.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(_stock);
        _stock.setBounds(1020, 290, 200, 30);

        img_stock2.setText("img_invoice");
        img_stock2.setBorder(new javax.swing.border.MatteBorder(null));
        img_stock2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                img_stock2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                img_stock2MouseExited(evt);
            }
        });
        getContentPane().add(img_stock2);
        img_stock2.setBounds(990, 40, 290, 300);

        _stock2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        _stock2.setForeground(new java.awt.Color(16, 13, 13));
        _stock2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _stock2.setText("Stock");
        _stock2.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(_stock2);
        _stock2.setBounds(1010, 340, 240, 45);

        _grn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        _grn.setForeground(new java.awt.Color(255, 255, 255));
        _grn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _grn.setText("GRN");
        _grn.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(_grn);
        _grn.setBounds(700, 640, 200, 30);

        img_grn2.setText("img_invoice");
        img_grn2.setBorder(new javax.swing.border.MatteBorder(null));
        img_grn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                img_grn2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                img_grn2MouseExited(evt);
            }
        });
        getContentPane().add(img_grn2);
        img_grn2.setBounds(660, 390, 290, 300);

        _grn2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        _grn2.setForeground(new java.awt.Color(16, 13, 13));
        _grn2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _grn2.setText("GRN");
        _grn2.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(_grn2);
        _grn2.setBounds(680, 690, 240, 45);

        _supplier2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        _supplier2.setForeground(new java.awt.Color(16, 13, 13));
        _supplier2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _supplier2.setText("SUPPLIER");
        _supplier2.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(_supplier2);
        _supplier2.setBounds(1010, 690, 240, 45);

        img_supplier2.setText("img_invoice");
        img_supplier2.setBorder(new javax.swing.border.MatteBorder(null));
        img_supplier2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                img_supplier2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                img_supplier2MouseExited(evt);
            }
        });
        getContentPane().add(img_supplier2);
        img_supplier2.setBounds(990, 390, 290, 300);

        _customer2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        _customer2.setForeground(new java.awt.Color(16, 13, 13));
        _customer2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _customer2.setText("CUSTOMER");
        _customer2.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(_customer2);
        _customer2.setBounds(340, 690, 240, 45);

        img_customer2.setText("img_invoice");
        img_customer2.setBorder(new javax.swing.border.MatteBorder(null));
        img_customer2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                img_customer2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                img_customer2MouseExited(evt);
            }
        });
        getContentPane().add(img_customer2);
        img_customer2.setBounds(320, 390, 290, 300);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(230, 0, 10, 770);

        Logo.setText("jLabel3");
        Logo.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(Logo);
        Logo.setBounds(30, 110, 160, 160);

        name.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        name.setForeground(new java.awt.Color(0, 0, 0));
        name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name.setText("jLabel3");
        name.setBorder(new javax.swing.border.MatteBorder(null));
        name.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(name);
        name.setBounds(110, 440, 110, 290);

        name1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        name1.setForeground(new java.awt.Color(0, 0, 0));
        name1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name1.setText("jLabel3");
        name1.setBorder(new javax.swing.border.MatteBorder(null));
        name1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(name1);
        name1.setBounds(10, 300, 110, 290);

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-40, 0, 1420, 780);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
       u.imageMethod("/img/exit002.png", jLabel2);
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        u.imageMethod("/img/exit004.png", jLabel2);
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        SystemClose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void img_stockMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img_stockMouseEntered
       changeLableSC(img_stock,_stock,img_stock2,_stock2,1);
    }//GEN-LAST:event_img_stockMouseEntered

    private void img_invoice2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img_invoice2MouseExited
       changeLableSC(img_invoice,_invoice,img_invoice2,_invoice2,2);
    }//GEN-LAST:event_img_invoice2MouseExited

    private void img_customerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img_customerMouseEntered
        changeLableSC(img_customer,_customer,img_customer2,_customer2,1);
    }//GEN-LAST:event_img_customerMouseEntered

    private void img_supplierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img_supplierMouseEntered
       changeLableSC(img_supplier,_supplier,img_supplier2,_supplier2,1);
    }//GEN-LAST:event_img_supplierMouseEntered

    private void img_itemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img_itemMouseEntered
       changeLableSC(img_item,_item,img_item2,_item2,1);
    }//GEN-LAST:event_img_itemMouseEntered

    private void img_grnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img_grnMouseEntered
         changeLableSC(img_grn,_grn,img_grn2,_grn2,1);
    }//GEN-LAST:event_img_grnMouseEntered

    private void img_invoiceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img_invoiceMouseEntered
        changeLableSC(img_invoice,_invoice,img_invoice2,_invoice2,1);
    }//GEN-LAST:event_img_invoiceMouseEntered

    private void img_item2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img_item2MouseExited
       changeLableSC(img_item,_item,img_item2,_item2,2);
    }//GEN-LAST:event_img_item2MouseExited

    private void img_stock2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img_stock2MouseExited
         changeLableSC(img_stock,_stock,img_stock2,_stock2,2);
    }//GEN-LAST:event_img_stock2MouseExited

    private void img_grn2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img_grn2MouseExited
      changeLableSC(img_grn,_grn,img_grn2,_grn2,2);
    }//GEN-LAST:event_img_grn2MouseExited

    private void img_supplier2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img_supplier2MouseExited
       changeLableSC(img_supplier,_supplier,img_supplier2,_supplier2,2);
    }//GEN-LAST:event_img_supplier2MouseExited

    private void img_customer2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img_customer2MouseExited
        changeLableSC(img_customer,_customer,img_customer2,_customer2,2);
    }//GEN-LAST:event_img_customer2MouseExited

    private void img_invoice2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img_invoice2MouseClicked
       invoice.getLoginInstance().setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_img_invoice2MouseClicked

    private void img_item2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img_item2MouseClicked
       item.getLoginInstance().setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_img_item2MouseClicked

    private void img_stock2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img_stock2MouseClicked
        stock.getLoginInstance().setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_img_stock2MouseClicked

    private void img_supplier2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img_supplier2MouseClicked
       supplier.getLoginInstance().setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_img_supplier2MouseClicked

    private void img_grn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img_grn2MouseClicked
        grn.getLoginInstance().setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_img_grn2MouseClicked

    private void img_customer2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img_customer2MouseClicked
       customer.getLoginInstance().setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_img_customer2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel _customer;
    private javax.swing.JLabel _customer2;
    private javax.swing.JLabel _grn;
    private javax.swing.JLabel _grn2;
    private javax.swing.JLabel _invoice;
    private javax.swing.JLabel _invoice2;
    private javax.swing.JLabel _item;
    private javax.swing.JLabel _item2;
    private javax.swing.JLabel _stock;
    private javax.swing.JLabel _stock2;
    private javax.swing.JLabel _supplier;
    private javax.swing.JLabel _supplier2;
    private javax.swing.JLabel img_customer;
    private javax.swing.JLabel img_customer2;
    private javax.swing.JLabel img_grn;
    private javax.swing.JLabel img_grn2;
    private javax.swing.JLabel img_invoice;
    private javax.swing.JLabel img_invoice2;
    private javax.swing.JLabel img_item;
    private javax.swing.JLabel img_item2;
    private javax.swing.JLabel img_stock;
    private javax.swing.JLabel img_stock2;
    private javax.swing.JLabel img_supplier;
    private javax.swing.JLabel img_supplier2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel name1;
    // End of variables declaration//GEN-END:variables

    //---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\ 
    /* *** >>> Date ------------>>> 
     * *** >>> What ------------>>> SystemClose()
     * *** >>> Why ------------->>>
     * *** >>> Parameters ------>>> no
     * *** >>> Status ---------->>>
     */
    //>>>>>>>>> System open <<<<<<<<<<<   
    void SystemClose() {
        int x = JOptionPane.showConfirmDialog(this, "Do you sure close Exit the Sysytem ?", "Exit System", JOptionPane.YES_NO_OPTION);
        if (JOptionPane.YES_OPTION == x) {
            this.dispose();
        } else if (JOptionPane.NO_OPTION == x) {
            setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
              u.imageMethod("/img/exit004.png", jLabel2);
        }
    }
    //>>>>>>>>> System close <<<<<<<<<<<       

//---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    

    
    
    public void changeLableSC(JLabel image1,JLabel name1,JLabel image2,JLabel name2,int inout){
      if(inout == 1){
          image1.setVisible(false);
          name1.setVisible(false);
          image2.setVisible(true);
          name2.setVisible(true);
      }else{
          image2.setVisible(false);
          name2.setVisible(false);
          image1.setVisible(true);
          name1.setVisible(true);
      }
    }

}
