/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com_jFream;

import com_class.DBClass;
import com_class.Universal;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CHETHANA
 */
public class supplier extends javax.swing.JFrame {
    static Universal u  = new Universal();
    public static int supId;

    public supplier() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        jScrollPane_supplier_name.setVisible(false);
        addTotableSearSupplier();
        jcheckbox_supplier.setVisible(true);
        u.imageMethod("/img/2222.jpg", jLabel1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane_supplier_name = new javax.swing.JScrollPane();
        jList_supplier_name = new javax.swing.JList();
        login_la_cloce = new javax.swing.JLabel();
        login_la_mini = new javax.swing.JLabel();
        supplier_b_enter = new javax.swing.JButton();
        supplier_b_delete = new javax.swing.JButton();
        supplier_b_update = new javax.swing.JButton();
        supplier_b_search = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        tx_supplier_name = new javax.swing.JTextField();
        tx_supplier_contact_number = new javax.swing.JTextField();
        tx_supplier_gmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tx_supplier_address = new javax.swing.JTextField();
        supplier_b_new = new javax.swing.JButton();
        jcheckbox_supplier = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtable_supplier = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1380, 768));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1380, 768));
        getContentPane().setLayout(null);

        jLayeredPane1.setBackground(new java.awt.Color(204, 204, 204));
        jLayeredPane1.setOpaque(true);

        jList_supplier_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jList_supplier_nameKeyPressed(evt);
            }
        });
        jScrollPane_supplier_name.setViewportView(jList_supplier_name);

        jLayeredPane1.add(jScrollPane_supplier_name);
        jScrollPane_supplier_name.setBounds(180, 110, 620, 131);

        login_la_cloce.setBackground(new java.awt.Color(102, 204, 255));
        login_la_cloce.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        login_la_cloce.setForeground(new java.awt.Color(0, 0, 0));
        login_la_cloce.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_la_cloce.setText("X");
        login_la_cloce.setOpaque(true);
        login_la_cloce.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_la_cloceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                login_la_cloceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                login_la_cloceMouseExited(evt);
            }
        });
        jLayeredPane1.add(login_la_cloce);
        login_la_cloce.setBounds(1330, 5, 30, 30);

        login_la_mini.setBackground(new java.awt.Color(102, 204, 255));
        login_la_mini.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        login_la_mini.setForeground(new java.awt.Color(0, 0, 0));
        login_la_mini.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_la_mini.setText("-");
        login_la_mini.setOpaque(true);
        login_la_mini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_la_miniMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                login_la_miniMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                login_la_miniMouseExited(evt);
            }
        });
        jLayeredPane1.add(login_la_mini);
        login_la_mini.setBounds(1300, 5, 30, 30);

        supplier_b_enter.setBackground(new java.awt.Color(255, 255, 255));
        supplier_b_enter.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        supplier_b_enter.setForeground(new java.awt.Color(0, 0, 0));
        supplier_b_enter.setText("Enter");
        supplier_b_enter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                supplier_b_enterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                supplier_b_enterMouseExited(evt);
            }
        });
        supplier_b_enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplier_b_enterActionPerformed(evt);
            }
        });
        jLayeredPane1.add(supplier_b_enter);
        supplier_b_enter.setBounds(840, 390, 180, 45);

        supplier_b_delete.setBackground(new java.awt.Color(255, 255, 255));
        supplier_b_delete.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        supplier_b_delete.setForeground(new java.awt.Color(0, 0, 0));
        supplier_b_delete.setText("Delete");
        supplier_b_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                supplier_b_deleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                supplier_b_deleteMouseExited(evt);
            }
        });
        supplier_b_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplier_b_deleteActionPerformed(evt);
            }
        });
        jLayeredPane1.add(supplier_b_delete);
        supplier_b_delete.setBounds(580, 390, 180, 45);

        supplier_b_update.setBackground(new java.awt.Color(255, 255, 255));
        supplier_b_update.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        supplier_b_update.setForeground(new java.awt.Color(0, 0, 0));
        supplier_b_update.setText("Update");
        supplier_b_update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                supplier_b_updateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                supplier_b_updateMouseExited(evt);
            }
        });
        supplier_b_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplier_b_updateActionPerformed(evt);
            }
        });
        jLayeredPane1.add(supplier_b_update);
        supplier_b_update.setBounds(320, 390, 180, 45);

        supplier_b_search.setBackground(new java.awt.Color(255, 255, 255));
        supplier_b_search.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        supplier_b_search.setForeground(new java.awt.Color(0, 0, 0));
        supplier_b_search.setText("Search");
        supplier_b_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supplier_b_searchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                supplier_b_searchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                supplier_b_searchMouseExited(evt);
            }
        });
        supplier_b_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplier_b_searchActionPerformed(evt);
            }
        });
        jLayeredPane1.add(supplier_b_search);
        supplier_b_search.setBounds(60, 390, 180, 45);
        jLayeredPane1.add(jSeparator1);
        jSeparator1.setBounds(0, 370, 1360, 10);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jLayeredPane1.add(jSeparator3);
        jSeparator3.setBounds(1060, 390, 10, 30);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jLayeredPane1.add(jSeparator4);
        jSeparator4.setBounds(280, 390, 10, 30);

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jLayeredPane1.add(jSeparator5);
        jSeparator5.setBounds(540, 390, 10, 30);

        jLabel2.setBackground(new java.awt.Color(102, 204, 255));
        jLabel2.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SUPPLIER");
        jLabel2.setOpaque(true);
        jLayeredPane1.add(jLabel2);
        jLabel2.setBounds(0, 0, 1360, 40);

        tx_supplier_name.setBackground(new java.awt.Color(255, 255, 255));
        tx_supplier_name.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tx_supplier_name.setForeground(new java.awt.Color(0, 0, 0));
        tx_supplier_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_supplier_nameActionPerformed(evt);
            }
        });
        tx_supplier_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tx_supplier_nameKeyPressed(evt);
            }
        });
        jLayeredPane1.add(tx_supplier_name);
        tx_supplier_name.setBounds(180, 78, 620, 35);

        tx_supplier_contact_number.setBackground(new java.awt.Color(255, 255, 255));
        tx_supplier_contact_number.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tx_supplier_contact_number.setForeground(new java.awt.Color(0, 0, 0));
        tx_supplier_contact_number.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tx_supplier_contact_numberKeyPressed(evt);
            }
        });
        jLayeredPane1.add(tx_supplier_contact_number);
        tx_supplier_contact_number.setBounds(180, 138, 620, 35);

        tx_supplier_gmail.setBackground(new java.awt.Color(255, 255, 255));
        tx_supplier_gmail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tx_supplier_gmail.setForeground(new java.awt.Color(0, 0, 0));
        tx_supplier_gmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tx_supplier_gmailKeyPressed(evt);
            }
        });
        jLayeredPane1.add(tx_supplier_gmail);
        tx_supplier_gmail.setBounds(180, 198, 620, 35);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Contact Number");
        jLayeredPane1.add(jLabel5);
        jLabel5.setBounds(40, 140, 140, 25);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Active OR Inactive");
        jLayeredPane1.add(jLabel6);
        jLabel6.setBounds(30, 320, 140, 25);

        tx_supplier_address.setBackground(new java.awt.Color(255, 255, 255));
        tx_supplier_address.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tx_supplier_address.setForeground(new java.awt.Color(0, 0, 0));
        tx_supplier_address.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tx_supplier_addressKeyPressed(evt);
            }
        });
        jLayeredPane1.add(tx_supplier_address);
        tx_supplier_address.setBounds(180, 258, 1150, 35);

        supplier_b_new.setBackground(new java.awt.Color(255, 255, 255));
        supplier_b_new.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        supplier_b_new.setForeground(new java.awt.Color(0, 0, 0));
        supplier_b_new.setText("New");
        supplier_b_new.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                supplier_b_newMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                supplier_b_newMouseExited(evt);
            }
        });
        supplier_b_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplier_b_newActionPerformed(evt);
            }
        });
        jLayeredPane1.add(supplier_b_new);
        supplier_b_new.setBounds(1100, 390, 180, 45);

        jcheckbox_supplier.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcheckbox_supplierKeyPressed(evt);
            }
        });
        jLayeredPane1.add(jcheckbox_supplier);
        jcheckbox_supplier.setBounds(180, 320, 40, 24);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Supplier Name");
        jLayeredPane1.add(jLabel10);
        jLabel10.setBounds(40, 80, 140, 25);
        jLayeredPane1.add(jSeparator2);
        jSeparator2.setBounds(0, 40, 1360, 10);

        jtable_supplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Contact Number", "Address", "Mail", "Is Active"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtable_supplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtable_supplierMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtable_supplier);
        if (jtable_supplier.getColumnModel().getColumnCount() > 0) {
            jtable_supplier.getColumnModel().getColumn(0).setMinWidth(50);
            jtable_supplier.getColumnModel().getColumn(0).setPreferredWidth(50);
            jtable_supplier.getColumnModel().getColumn(0).setMaxWidth(50);
            jtable_supplier.getColumnModel().getColumn(2).setMinWidth(170);
            jtable_supplier.getColumnModel().getColumn(2).setPreferredWidth(170);
            jtable_supplier.getColumnModel().getColumn(2).setMaxWidth(170);
            jtable_supplier.getColumnModel().getColumn(3).setMinWidth(450);
            jtable_supplier.getColumnModel().getColumn(3).setPreferredWidth(450);
            jtable_supplier.getColumnModel().getColumn(3).setMaxWidth(450);
            jtable_supplier.getColumnModel().getColumn(5).setMinWidth(100);
            jtable_supplier.getColumnModel().getColumn(5).setPreferredWidth(100);
            jtable_supplier.getColumnModel().getColumn(5).setMaxWidth(100);
        }

        jLayeredPane1.add(jScrollPane1);
        jScrollPane1.setBounds(60, 470, 1260, 280);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Supplier Address");
        jLayeredPane1.add(jLabel7);
        jLabel7.setBounds(30, 260, 140, 25);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Mail");
        jLayeredPane1.add(jLabel8);
        jLabel8.setBounds(40, 200, 140, 25);

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jLayeredPane1.add(jSeparator6);
        jSeparator6.setBounds(800, 390, 10, 30);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("jLabel1");
        jLayeredPane1.add(jLabel1);
        jLabel1.setBounds(0, 40, 1360, 730);

        getContentPane().add(jLayeredPane1);
        jLayeredPane1.setBounds(0, 0, 1360, 760);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_la_cloceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_la_cloceMouseClicked
        SystemClose();
    }//GEN-LAST:event_login_la_cloceMouseClicked

    private void login_la_cloceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_la_cloceMouseEntered
        login_la_cloce.setBackground(Color.red);
    }//GEN-LAST:event_login_la_cloceMouseEntered

    private void login_la_cloceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_la_cloceMouseExited
        login_la_cloce.setBackground(new Color(102, 204, 255));
    }//GEN-LAST:event_login_la_cloceMouseExited

    private void login_la_miniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_la_miniMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_login_la_miniMouseClicked

    private void login_la_miniMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_la_miniMouseEntered
        login_la_mini.setBackground(Color.gray);
    }//GEN-LAST:event_login_la_miniMouseEntered

    private void login_la_miniMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_la_miniMouseExited
        login_la_mini.setBackground(new Color(102, 204, 255));
    }//GEN-LAST:event_login_la_miniMouseExited

    private void supplier_b_enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplier_b_enterActionPerformed
        if (tx_supplier_name.getText().trim().isEmpty()) {
            tx_supplier_name.grabFocus();
        } else if (tx_supplier_contact_number.getText().trim().isEmpty()) {
            tx_supplier_contact_number.grabFocus();
        } else if (tx_supplier_gmail.getText().trim().isEmpty()) {
            tx_supplier_gmail.grabFocus();
        } else if (tx_supplier_address.getText().trim().isEmpty()) {
            tx_supplier_address.grabFocus();
        } else if (!(tx_supplier_address.getText().trim().isEmpty() & tx_supplier_contact_number.getText().trim().isEmpty() & tx_supplier_gmail.getText().trim().isEmpty()
                & tx_supplier_name.getText().trim().isEmpty())) {
            addToTable();
        }
        supplier_b_enter.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_supplier_b_enterActionPerformed

    private void supplier_b_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplier_b_deleteActionPerformed

        if (!(tx_supplier_address.getText().trim().isEmpty() & tx_supplier_contact_number.getText().trim().isEmpty() & tx_supplier_gmail.getText().trim().isEmpty()
                & tx_supplier_name.getText().trim().isEmpty())) {
            int x = JOptionPane.showConfirmDialog(this, "Do you sure Delete this supplier ?", "Exit Interface", JOptionPane.YES_NO_OPTION);
            if (JOptionPane.YES_OPTION == x) {
                jcheckbox_supplier.setSelected(false);
                updateSupplier("delete");
                JOptionPane.showConfirmDialog(this, "Supplier Deleted ?", "Delete", JOptionPane.OK_OPTION);
                addTotableSearSupplier();
                clearemployeeFields();
            } else if (JOptionPane.NO_OPTION == x) {
                setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
            }
        }else{
            JOptionPane.showConfirmDialog(this, "Fill the details ?", "NOT Complet", JOptionPane.OK_OPTION);
        }
          supplier_b_delete.setBackground(new Color(255, 255, 255));

    }//GEN-LAST:event_supplier_b_deleteActionPerformed

    private void supplier_b_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplier_b_updateActionPerformed
        if (tx_supplier_name.getText().trim().isEmpty()) {
            tx_supplier_name.grabFocus();
        } else if (tx_supplier_contact_number.getText().trim().isEmpty()) {
            tx_supplier_contact_number.grabFocus();
        } else if (tx_supplier_gmail.getText().trim().isEmpty()) {
            tx_supplier_gmail.grabFocus();
        } else if (tx_supplier_address.getText().trim().isEmpty()) {
            tx_supplier_address.grabFocus();
        } else if (!(tx_supplier_address.getText().trim().isEmpty() & tx_supplier_contact_number.getText().trim().isEmpty() & tx_supplier_gmail.getText().trim().isEmpty()
                & tx_supplier_name.getText().trim().isEmpty())) {
            updateSupplier("update");
        }
        supplier_b_update.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_supplier_b_updateActionPerformed

    private void supplier_b_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplier_b_searchActionPerformed
        if (!tx_supplier_name.getText().trim().isEmpty()) {
            addTotableSearSupplierSearchName(tx_supplier_name.getText());
        } else {
            tx_supplier_name.grabFocus();
        }
        supplier_b_search.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_supplier_b_searchActionPerformed

    private void tx_supplier_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_supplier_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_supplier_nameActionPerformed

    private void tx_supplier_nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tx_supplier_nameKeyPressed
        if (tx_supplier_name.getText().isEmpty()) {
            addTotableSearSupplier();
        } else {
            TXValidaton(evt, tx_supplier_name, 50, "A");

            if (evt.getKeyCode() == 10) {
                if (!tx_supplier_name.getText().isEmpty()) {
                    tx_supplier_contact_number.grabFocus();
                } else {
                    tx_supplier_name.grabFocus();
                }
            }

            if (evt.getKeyCode() == KeyEvent.VK_DOWN || evt.getKeyCode() == KeyEvent.VK_UP) {
                jList_supplier_name.grabFocus();
                jList_supplier_name.setSelectedIndex(0);
                jScrollPane_supplier_name.setVisible(true);
            } else if (!(tx_supplier_name.getText().trim().isEmpty())) {
                searchANDListSupplier("supplier", "name", tx_supplier_name.getText(), jList_supplier_name);
            }
        }
    }//GEN-LAST:event_tx_supplier_nameKeyPressed

    private void tx_supplier_contact_numberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tx_supplier_contact_numberKeyPressed
        TXValidaton(evt, tx_supplier_contact_number, 11, "N");
        if (evt.getKeyCode() == 10) {
            if (!tx_supplier_contact_number.getText().isEmpty()) {
                tx_supplier_gmail.grabFocus();
            } else {
                tx_supplier_contact_number.grabFocus();
            }
        }
    }//GEN-LAST:event_tx_supplier_contact_numberKeyPressed

    private void tx_supplier_addressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tx_supplier_addressKeyPressed
        TXValidaton(evt, tx_supplier_address, 170, "NA");
        if (evt.getKeyCode() == 10) {
            if (!tx_supplier_address.getText().isEmpty()) {
                jcheckbox_supplier.setSelected(true);
                supplier_b_enter.doClick();
                buttonMouseEnEx(supplier_b_enter, 0);
            } else {
                tx_supplier_address.grabFocus();
            }
             buttonMouseEnEx(supplier_b_enter,1);
        }
        
    }//GEN-LAST:event_tx_supplier_addressKeyPressed

    private void supplier_b_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplier_b_newActionPerformed
        int x = JOptionPane.showConfirmDialog(this, "Do you want add new Supplier ?", "Add New One", JOptionPane.YES_NO_OPTION);
        if (JOptionPane.YES_OPTION == x) {
            clearemployeeFields();
            addTotableSearSupplier();
            tx_supplier_name.grabFocus();
        } else if (JOptionPane.NO_OPTION == x) {
            setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        }
        supplier_b_new.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_supplier_b_newActionPerformed

    private void supplier_b_searchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplier_b_searchMouseEntered
        buttonMouseEnEx(supplier_b_search, 0);
    }//GEN-LAST:event_supplier_b_searchMouseEntered

    private void supplier_b_searchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplier_b_searchMouseExited
        buttonMouseEnEx(supplier_b_search, 1);
    }//GEN-LAST:event_supplier_b_searchMouseExited

    private void supplier_b_updateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplier_b_updateMouseEntered
        buttonMouseEnEx(supplier_b_update, 0);
    }//GEN-LAST:event_supplier_b_updateMouseEntered

    private void supplier_b_updateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplier_b_updateMouseExited
        buttonMouseEnEx(supplier_b_update, 1);
    }//GEN-LAST:event_supplier_b_updateMouseExited

    private void supplier_b_deleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplier_b_deleteMouseEntered
        buttonMouseEnEx(supplier_b_delete, 0);
    }//GEN-LAST:event_supplier_b_deleteMouseEntered

    private void supplier_b_deleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplier_b_deleteMouseExited
        buttonMouseEnEx(supplier_b_delete, 1);
    }//GEN-LAST:event_supplier_b_deleteMouseExited

    private void supplier_b_enterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplier_b_enterMouseEntered
        buttonMouseEnEx(supplier_b_enter, 0);
    }//GEN-LAST:event_supplier_b_enterMouseEntered

    private void supplier_b_enterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplier_b_enterMouseExited
        buttonMouseEnEx(supplier_b_enter, 1);
    }//GEN-LAST:event_supplier_b_enterMouseExited

    private void tx_supplier_gmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tx_supplier_gmailKeyPressed

        TXValidaton(evt, tx_supplier_gmail, 70, "NA");
        if (evt.getKeyCode() == 10) {
            if (!tx_supplier_gmail.getText().trim().isEmpty()) {
                tx_supplier_address.grabFocus();
            } else {
                tx_supplier_gmail.grabFocus();
            }
        }
    }//GEN-LAST:event_tx_supplier_gmailKeyPressed

    private void jList_supplier_nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jList_supplier_nameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!jList_supplier_name.isSelectionEmpty()) {
                tx_supplier_name.setText(jList_supplier_name.getSelectedValue().toString());
                jScrollPane_supplier_name.setVisible(false);
                tx_supplier_contact_number.grabFocus();
            }
        }
    }//GEN-LAST:event_jList_supplier_nameKeyPressed

    private void supplier_b_searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplier_b_searchMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_supplier_b_searchMouseClicked

    private void jtable_supplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtable_supplierMouseClicked
        DefaultTableModel tlModel = (DefaultTableModel) jtable_supplier.getModel();
        supId  = Integer.parseInt(tlModel.getValueAt(jtable_supplier.getSelectedRow(),0).toString());
        String t_name = tlModel.getValueAt(jtable_supplier.getSelectedRow(), 1).toString();
        String t_tel = tlModel.getValueAt(jtable_supplier.getSelectedRow(), 2).toString();
        String t_gmail = tlModel.getValueAt(jtable_supplier.getSelectedRow(), 3).toString();
        String t_address = tlModel.getValueAt(jtable_supplier.getSelectedRow(), 4).toString();
        String t_isactive = tlModel.getValueAt(jtable_supplier.getSelectedRow(), 5).toString();

        tx_supplier_name.setText(t_name);
        tx_supplier_contact_number.setText(t_tel);
        tx_supplier_gmail.setText(t_gmail);
        tx_supplier_address.setText(t_address);
        if (t_isactive.equals("Active")) {
            jcheckbox_supplier.setSelected(true);
        } else {
            jcheckbox_supplier.setSelected(false);
        }

    }//GEN-LAST:event_jtable_supplierMouseClicked

    private void supplier_b_newMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplier_b_newMouseEntered
        buttonMouseEnEx(supplier_b_new, 0);
    }//GEN-LAST:event_supplier_b_newMouseEntered

    private void supplier_b_newMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplier_b_newMouseExited
        buttonMouseEnEx(supplier_b_new, 1);
    }//GEN-LAST:event_supplier_b_newMouseExited

    private void jcheckbox_supplierKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcheckbox_supplierKeyPressed
       if (evt.getKeyCode() == 10) {
           supplier_b_enter.doClick();
           buttonMouseEnEx(supplier_b_enter, 0);
        }
    }//GEN-LAST:event_jcheckbox_supplierKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new supplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JList jList_supplier_name;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane_supplier_name;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JCheckBox jcheckbox_supplier;
    private javax.swing.JTable jtable_supplier;
    private javax.swing.JLabel login_la_cloce;
    private javax.swing.JLabel login_la_mini;
    private javax.swing.JButton supplier_b_delete;
    private javax.swing.JButton supplier_b_enter;
    private javax.swing.JButton supplier_b_new;
    private javax.swing.JButton supplier_b_search;
    private javax.swing.JButton supplier_b_update;
    private javax.swing.JTextField tx_supplier_address;
    private javax.swing.JTextField tx_supplier_contact_number;
    private javax.swing.JTextField tx_supplier_gmail;
    private javax.swing.JTextField tx_supplier_name;
    // End of variables declaration//GEN-END:variables

//---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\ 
    /* *** >>> Date ------------>>> 
     * *** >>> What ------------>>> Singltan class 
     * *** >>> Why ------------->>> ek object ekk hdnn
     * *** >>> Parameters ------>>>
     * *** >>> Status ---------->>>
     */
//>>>>>>>>> Get Instance <<<<<<<<<<<  
    private static supplier log = new supplier();

    public static supplier getLoginInstance() {
        return log;
    }
//>>>>>>>>> Get Instance <<<<<<<<<<<         

//---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\     
   


//---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\ 
    /* *** >>> Date ------------>>> 
     * *** >>> What ------------>>> TXValidaton()
     * *** >>> Why ------------->>>
     * *** >>> Parameters ------>>> KeyEvent evt//JTextField txName//int lenth//String type
     * *** >>> Status ---------->>>
     */
    //>>>>>>>>> TXValidaton open <<<<<<<<<<<   
    private void TXValidaton(KeyEvent evt, JTextField txName, int lenth, String type) {
        int iNumber = evt.getKeyCode();
        if (txName.getText().length() <= lenth) {
            if (type.equals("N")) {

                if ((iNumber >= 96 & iNumber <= 105) | (iNumber >= 48 & iNumber <= 57) | (iNumber == 8) | (iNumber == 17) | (iNumber == 86)) {
                    txName.setEditable(true);
                } else {
                    txName.setEditable(false);
                }

            }
            if (type.equals("A")) {

                if ((iNumber >= 65 & iNumber <= 90) | (iNumber == 8) | (iNumber == 32) | (iNumber == 46) | (iNumber == 17)) {
                    txName.setEditable(true);
                } else {
                    txName.setEditable(false);
                }

            }
            if (type.equals("NA")) {

                if ((iNumber >= 96 & iNumber <= 105) | (iNumber >= 48 & iNumber <= 57) | (iNumber >= 65 & iNumber <= 90) | (iNumber == 8) | (iNumber == 45) | (iNumber == 32) | (iNumber == 44) | (iNumber == 46) | (iNumber == 47)) {
                    txName.setEditable(true);
                } else {
                    txName.setEditable(false);
                }

            }

        } else if ((iNumber == 8)) {
            txName.setEditable(true);
        } else {
            txName.setEditable(false);
        }
    }
    //>>>>>>>>> TXValidaton close <<<<<<<<<<<       
//---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\     

//---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\ 
    /* *** >>> Date ------------>>> 
     * *** >>> What ------------>>> clearemployeeFields()
     * *** >>> Why ------------->>>
     * *** >>> Parameters ------>>> 
     * *** >>> Status ---------->>>
     */
    //>>>>>>>>> clearemployeeFields cloce <<<<<<<<<<<        
    private void clearemployeeFields() {
        tx_supplier_name.setText(null);
        tx_supplier_address.setText(null);
        tx_supplier_gmail.setText(null);
        tx_supplier_contact_number.setText(null);
        jcheckbox_supplier.setSelected(false);
        supId = 0;
        tx_supplier_name.grabFocus();
    }
    //>>>>>>>>> clearemployeeFields close <<<<<<<<<<<       
//---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\     

//---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\ 
    /* *** >>> Date ------------>>> 
     * *** >>> What ------------>>> SystemClose()
     * *** >>> Why ------------->>>
     * *** >>> Parameters ------>>> no
     * *** >>> Status ---------->>>
     */
    //>>>>>>>>> System open <<<<<<<<<<<   
    void SystemClose() {
        int x = JOptionPane.showConfirmDialog(this, "Do you sure close Employee Interface ?", "Exit Interface", JOptionPane.YES_NO_OPTION);
        if (JOptionPane.YES_OPTION == x) {
            this.dispose();
        } else if (JOptionPane.NO_OPTION == x) {
            setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
            login_la_cloce.setBackground(new Color(255, 255, 255));
        }
    }
    //>>>>>>>>> System close <<<<<<<<<<<       

//---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\     

    
    
//---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\ 
    /* *** >>> Date ------------>>> 
     * *** >>> What ------------>>> buttonMouseEnEx()
     * *** >>> Why ------------->>>
     * *** >>> Parameters ------>>> JButton buttonName, int x
     * *** >>> Status ---------->>>
     */
    //>>>>>>>>> buttonMouseEnEx open <<<<<<<<<<<    
    private void buttonMouseEnEx(JButton buttonName, int x) {
        if (x == 0) {
            buttonName.setBackground(new Color(84, 245, 214));
        } else {
            buttonName.setBackground(new Color(225, 225, 225));
        }
    }
    //>>>>>>>>> buttonMouseEnEx close <<<<<<<<<<<       

//---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\     

    
    
//---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\ 
    /* *** >>> Date ------------>>> 
     * *** >>> What ------------>>> addToTable()
     * *** >>> Why ------------->>>
     * *** >>> Parameters ------>>> 
     * *** >>> Status ---------->>>
     */
    //>>>>>>>>> addToTable open <<<<<<<<<<<        
    private void addToTable() {
        try {
            String name = tx_supplier_name.getText();
            String tell = tx_supplier_contact_number.getText();
            String address = tx_supplier_address.getText();
            String gmail = tx_supplier_gmail.getText();
            DBClass.putData("insert into supplier (name,tell,address,gmail,status) values('" + name + "' , '" + tell + "' , '" + address + "' ,'" + gmail + "' ,'1')");
            clearemployeeFields();
            addTotableSearSupplier();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Bug Error SupplierTableInsert !!! \n addToTable() \n" + ex, "Error Massage", JOptionPane.ERROR_MESSAGE);
        }
    }
    //>>>>>>>>> addToTable close <<<<<<<<<<<       

//---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\     

    
    
  
    
    
//---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\ 
    /* *** >>> Date ------------>>> 
     * *** >>> What ------------>>> addTotableSearSupplier()
     * *** >>> Why ------------->>>
     * *** >>> Parameters ------>>> 
     * *** >>> Status ---------->>>
     */
    //>>>>>>>>> addTotableSearSupplier open <<<<<<<<<<<        
    private void addTotableSearSupplier() {
        try {
            ResultSet rs = DBClass.getData("select * from supplier order by idsupplier");
            DefaultTableModel dm = (DefaultTableModel) jtable_supplier.getModel();
            // jtable_supplier.removeAll();
            dm.setRowCount(0);
            if (DBClass.r.isBeforeFirst() == true) {
                while (rs.next()) {
                    Vector v = new Vector();
                    v.add(rs.getString("idsupplier"));
                    v.add(rs.getString("name"));
                    v.add(rs.getString("tell"));
                    v.add(rs.getString("address"));
                    v.add(rs.getString("gmail"));
                   if (rs.getInt("status") == 1) {
                        v.add("Active");
                        dm.addRow(v);
                    } else if (rs.getInt("status") == 0) {
                        v.add("Inactive");
                        dm.addRow(v);
                    }
                }
            }

        } catch (SQLException sqle) {
            JOptionPane.showMessageDialog(this, "Supplier Table Error ::\n addTotableSearSupplier() \n" + sqle, "Error Massage", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Supplier Table Error ::\n addTotableSearSupplier() \n" + e, "Error Massage", JOptionPane.ERROR_MESSAGE);
        }
    }
    //>>>>>>>>> addTotableSearSupplier close <<<<<<<<<<<       

//---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\     

    
    
    
//---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\ 
    /* *** >>> Date ------------>>> 
     * *** >>> What ------------>>> searchANDListSupplier()
     * *** >>> Why ------------->>>
     * *** >>> Parameters ------>>> String supplier, String name, String text, JList jList_supplier_name
     * *** >>> Status ---------->>>
     */
    //>>>>>>>>> searchANDListSupplier open <<<<<<<<<<<        
    private void searchANDListSupplier(String supplier, String name, String text, JList jList_supplier_name) {
        try {
            DBClass.getData("select " + name + " from " + supplier + " where " + name + " like '" + text + "%' order by " + name);
            Vector v = new Vector();
            jList_supplier_name.removeAll();
            if (DBClass.r.isBeforeFirst() == true) {
                while (DBClass.r.next()) {
                    v.add(DBClass.r.getString(name));
                    jList_supplier_name.setListData(v);
                }
            } else {
                jList_supplier_name.setListData(v);
            }
        } catch (SQLException sqle) {
            JOptionPane.showMessageDialog(null, "Bug Error searchANDList!!! \n " + sqle, "Error Massage", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Bug Error searchANDList!!! \n " + e, "Error Massage", JOptionPane.ERROR_MESSAGE);
        }
    }
    //>>>>>>>>> searchANDListSupplier close <<<<<<<<<<<       

//---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\     

    
    
//---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\ 
    /* *** >>> Date ------------>>> 
     * *** >>> What ------------>>> addTotableSearSupplierSearchName()
     * *** >>> Why ------------->>>
     * *** >>> Parameters ------>>> String name
     * *** >>> Status ---------->>>
     */
    //>>>>>>>>> addTotableSearSupplierSearchName open <<<<<<<<<<<        
    private void addTotableSearSupplierSearchName(String name) {
        try {
            ResultSet rs = DBClass.getData("select * from supplier where name='" + name + "' order by name");
            DefaultTableModel dm = (DefaultTableModel) jtable_supplier.getModel();
            // jtable_supplier.removeAll();
            dm.setRowCount(0);
            if (DBClass.r.isBeforeFirst() == true) {
                while (rs.next()) {
                    Vector v = new Vector();
                    v.add(rs.getString("idsupplier"));
                    v.add(rs.getString("name"));
                    v.add(rs.getString("tell"));
                    v.add(rs.getString("address"));
                    v.add(rs.getString("gmail"));
                    if (rs.getInt("status") == 1) {
                        v.add("Active");
                        dm.addRow(v);
                    } else if (rs.getInt("status") == 0) {
                        v.add("Inactive");
                        dm.addRow(v);
                    }
                }
            }

        } catch (SQLException sqle) {
            JOptionPane.showMessageDialog(this, "Supplier Table Error ::\n addTotableSearSupplier() \n" + sqle, "Error Massage", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Supplier Table Error ::\n addTotableSearSupplier() \n" + e, "Error Massage", JOptionPane.ERROR_MESSAGE);
        }
    }
    //>>>>>>>>> addTotableSearSupplierSearchName close <<<<<<<<<<<       

//---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\     

    
    
//---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\ 
    /* *** >>> Date ------------>>> 
     * *** >>> What ------------>>> updateSupplier()
     * *** >>> Why ------------->>>
     * *** >>> Parameters ------>>> 
     * *** >>> Status ---------->>>
     */
    //>>>>>>>>> updateSupplier open <<<<<<<<<<<        
    private void updateSupplier(String qurName) {
        String name = tx_supplier_name.getText();
        String tell = tx_supplier_contact_number.getText();
        String address = tx_supplier_address.getText();
        String gmail = tx_supplier_gmail.getText();

        boolean b = jcheckbox_supplier.isSelected();
        int bb = 1;
        if (b == false) {
            bb = 0;
        }
        try {
             if (qurName.equals("update")) {
               DBClass.putData("update supplier set name='" + name + "',tell='" + tell + "',address='" + address + "',gmail='" + gmail + "',status ='" + bb + "' where  idsupplier ='" + supId + "' ");
             } else if (qurName.equals("delete")) {
                   DBClass.putData("update supplier set name='" + name + "',tell='" + tell + "',address='" + address + "',gmail='" + gmail + "',status ='2' where  idsupplier ='" + supId + "' ");
            }
            clearemployeeFields();
            addTotableSearSupplier();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Bug Error supplierTableUpdate !!! \n " + ex, "Error Massage", JOptionPane.ERROR_MESSAGE);
        }
    }
    //>>>>>>>>> updateSupplier close <<<<<<<<<<<       

//---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\     

    
    
}
